### ISSUE TITLE
XP support?

### ISSUE THREAD

**Issue by tumagonx** [kenjiuno/ThumbGensPack#3]
I know in your readme this was for Windows 7 but CmdThumbGen support IExtractImage (among others) which XP support.
My goal is to use Imagemagick's convert.exe to thumbnail SVG image

Steps:
- compile with VS2010
- regsvr32 cmdthumbgen.dll
- setup HKLM\HIRAOKA HYPERS TOOLS, Inc.\CmdThumbGen\FileExts.svg
  "" = C:\IM\convert.exe "%1!s!" -resize 96x96 "%2!s!"
- I also need to register HKCR.svg\shellex{BB2E617C-0920-11D1-9A0B-00C04FC2D6C1} to CMdThumbGen CLSID {93FB1A02-084D-43B4-A69F-65D8B86F2AB3}

First issue:
IM convert need output file to have extension (.bmp) not just UUID, i put in gene.h as workaround
wcscat(wcId,L".bmp");

Second issue:
When observed with MS Filemon when view thumbnail of SVG image in explorer:
%TEMP%\UUID.bmp was created then deleted, but no thumbnail icon generated in explorer

Any ideas?

**Comment by kenjiuno** [comment]
Ok, I'll check it...

**Comment by kenjiuno** [comment]
Hi.

I could reproduce your problem on Win 8.1.

Try like this:
`"C:\IM\convert.exe" "%1!s!" -resize 96x96 "bmp3:%2!s!"`

As you mentioned, file extension isn't set in `%2!s!`. [This](http://stackoverflow.com/a/16689602) answer helped us. Prefix `bmp:`

And output is 32-bpp bitmap. LoadImage seems to fail loading it. [This](http://www.imagemagick.org/Usage/formats/#bmp) page helped in this case. Use `bmp3:` instead of `bmp:`.

**Comment by tumagonx** [comment]
Cool, it works now!

thank you!
